"""Add end_time and duration to Event model

Revision ID: 06438e9b749c
Revises: 96ae6abe410e
Create Date: 2024-07-09 22:12:50.625862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06438e9b749c'
down_revision = '96ae6abe410e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Interval(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_access_token', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('spotify_refresh_token', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('spotify_refresh_token')
        batch_op.drop_column('spotify_access_token')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
