"""Initial migration

Revision ID: 3b5af10cc3b6
Revises: e8baa2df4314
Create Date: 2024-07-12 14:31:20.552155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5af10cc3b6'
down_revision = 'e8baa2df4314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###
